- hosts: web
  tasks:
   - name: Install  Packages
     yum: pkg={{ item.packagename }} state=installed update_cache=true
     with_items:
       - { packagename: 'docker' }
       - { packagename: 'etcd' }
       - { packagename: 'kubernetes' }
       - { packagename: 'cockpit' }
       - { packagename: 'cockpit-kubernetes' }
    

   - name: Restart cockpit 
     service: name=cockpit state=restarted enabled=yes

   - name: Restart cockpit-kubernetes
     service: name=cockpit-kubernetes state restarted enabled=yes


