- hosts: web
  tasks:
   - name: Install  Packages
     yum: pkg={{ item.packagename }} state=installed update_cache=true
     with_items:
       - { packagename: 'docker' }
       - { packagename: 'etcd' }
       - { packagename: 'kubernetes' }
       - { packagename: 'cockpit' }
       - { packagename: 'cockpit-kubernetes' }
     notify:
     - restart service
  handlers:

   - name: restart service 
     service: name=cockpit state=restarted 
     service: name=cockpit-kubernetes state=restarted


