- hosts: web
  tasks:
   - name: Install  Packages
     yum: pkg={{ item.packagename }} state=installed update_cache=true
     with_items:
       - { packagename: 'docker' }
       - { packagename: 'etcd' }
       - { packagename: 'kubernetes' }
       - { packagename: 'cockpit' }
       - { packagename: 'cockpit-kubernetes' }

  tasks:
   -name: Restart Services
    service: name={{ item.packagename }} state=restarted
    with_items:
      - { packagename: 'docker' }
      - { packagename: 'etcd' }
      - { packagename: 'kubernetes' }
      - { packagename: 'cockpit' }
      - { packagename: 'cockpit-kubernetes' }

