---
- hosts: web
  tasks:

    - name: Deploy SAR
      yum: pkg=sysstat state=installed update_cache=true
      when:
      - ansible_distribution == "CentOS"    

    

    - name: Average Memory
      command: sar -r -q -n DEV
      register: memory

    - debug: msg=" Average Memory Utilization is {{memory.stdout}}"

    - local_action: copy content="{{ memory.stdout }}" dest="/root/results/memory.csv"

