---
- hosts: web
  tasks:
   - name: Install required package
     action: >
        {{ ansible_pkg_mgr }} name={{ item }} state=installed 
     with_items:
       - git
       - wget

   - name: Deploy Sample Repo
     template: src=template/galera.repo.j2 dest=/etc/yum.repos.d/galera.repo
